</div><!-- end mainheader -->
</div><!-- end header -->
<div class="authorsportrait">
    <img src="/images/picture_1.jpg" width="77" height="133" alt="Author"/>
    <a></a>
    <img src="/images/picture_1.gif" width="71" height="122" alt="Author"/>
</div>
<div class="footer">

    <a>Free Website Templates</a>
    <a>bestsellers</a> &nbsp;
    <a>magazines</a> &nbsp;
    <a>e-books</a> &nbsp;
    <a>contact</a> &nbsp;
</div><!-- end footer -->
</div><!-- end wrapper -->
</body>
</html>