<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Books online</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="/style.css" rel="stylesheet" type="text/css"/>
</head>

<body>
<div class="wrapper">
    <div class="header">
        <div class="menu">
            <h1><a><img src="/images/logo.gif" width="121" height="22" alt="Books Online"/></a></h1>
            <ul class="nav lightblue">
                <li><a href="/books">Книги</a></li>
                <li><a href="/authors">Авторы</a></li>
                <li><a href="/readers">Читатели</a></li>
                <li><a href="/subscription/authors">Подписки по авторам</a></li>
                <li><a href="/subscription/categories">Подписки по категориям</a></li>
            </ul>
            <ul class="nav yellow">
                <li><h2 class="categories">Категории</h2></li>
                <?php foreach ($categories as $category) : ?>
                    <li><a href="/category/view/<?php echo $category['id']; ?>"><?php echo $category['title']; ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div><!-- end menu -->
        <div class="mainheader">
            <div class="navtop">
                <a>&nbsp;</a>
                <a href="/user/login">Войти</a>
            </div>
            <div>
                <div class="exploretext">
                    <div class="boy"></div>
                    <div><h2><img src="/images/title_explore.gif" width="185" height="20" alt="explore your knowledge"/>
                        </h2>
                        <ul id="explore">
                        </ul>
                    </div>
                    <div class="girl"></div>
                </div>
            </div>
            <div class="divider"></div>
            <div class="searchbar">
                <form action="/" method="post">
                    <input name="title" type="text" value="Title:" class="text"/>
                    <input name="author" type="text" value="Author:" class="text"/>
                    <input type="submit" value="Go" class="submit"/>
                </form>
            </div><!-- end searchbar -->
